import ProjectDescription
import ProjectDescriptionHelpers

let executables: [Path] = [
    "App",
]

let productFeatures: [Path] = [
    "Features/Home",
]

let foundationFeatures: [Path] = [
    "Features/Foundation/Networking",
    "Features/Foundation/SMSCore",
]

let workspace = Workspace(
    name: "CurrencyConverter",
    projects: executables + productFeatures + foundationFeatures,
    schemes: [],
    additionalFiles: [
        "README.md",
        ".swiftformat",
        ".swiftlint.yml",
        ".swift-version"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .all,
            testLanguage: .init(identifier: "en"),
            testRegion: "US"
        )
    )
)
