import ProjectDescription
import ProjectDescriptionHelpers

let executables: [Path] = [
    "App",
]

let productFeatures: [Path] = [
    "Features/Home",
]

//let foundationFeatures: [Path] = [
//    "Features/Foundation/CDMRuntime",
//]

let workspace = Workspace(
    name: "CurrencyConverter",
    projects: executables + productFeatures,
    schemes: [],
    additionalFiles: [
        "README.md",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled(
            codeCoverageMode: .all,
            testLanguage: .init(identifier: "en"),
            testRegion: "US"
        )
    )
)
